ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'CONFIRMED' AFTER 'PENDING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'SHIPPED' AFTER 'PROCESSING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'DELIVERED' AFTER 'SHIPPED';

ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'CREATED' BEFORE 'PENDING';

ALTER TABLE "Order" ALTER COLUMN "paymentStatus" SET DEFAULT 'CREATED';
